apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: testing
    hello: bye
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["nginx"]
    args: ["-g", "daemon off;", "-q"]
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox
