apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 123nginx
  name: 123nginx
spec:
  containers:
  - image: nginx
    name: 123nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
