apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: multi-busy
spec:
  containers:
  - command: 
    - echo
    - hello
    - sleep
    - "3600"
    image: busybox
    name: busybox1
  - command:
    - echo
    - hello
    - sleep
    - "3600"
    image: busybox
    name: busybox2
